stages:
  - build
  - test
  - deploy

# 1️⃣ Build Stage
build-job:
  stage: build
  image: node:18
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Building the project..."
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main

# 2️⃣ Test Stage
test-job:
  stage: test
  image: node:18
  script:
    - echo "Running tests..."
    - npm test
  only:
    - main

# 3️⃣ Deploy Stage
deploy-job:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying the project..."
    - mkdir deploy_output
    - cp -r dist/* deploy_output/
    - echo "Deployment successful!"
  only:
    - main
